---
- name: Отправка приватных ключей пользователей
  block:
    - name: Архивирование файлов rsa_id
      archive:
        path: /root/rsa_keys/*
        dest: /root/rsa_keys.tgz
        format: gz

    - name: Удаление директории rsa_keys
      file:
        path: /root/rsa_keys
        state: absent

    - name: Получение архива rsa_keys.tgz
      fetch:
        src: /root/rsa_keys.tgz
        dest: ../
        flat: yes
      when: fetch_to_host == true

    - name: Отправка ключей на ftp сервер
      command: "curl -T /root/rsa_keys.tgz -u {{ ftp_username }}:{{ ftp_password }} ftp://10.249.254.252:14440"
      when: transfer_keys_to_ftp == true

    - name: Удаление rsa_keys.tgz
      file:
        path: /root/rsa_keys.tgz
        state: absent